### ISSUE TITLE
IndexError: list index out of range when trying to convert a 1.16.3 map

### ISSUE THREAD

**Issue by riosdev** [jonajames/mc2mt#4]
Hi, I am trying to convert the "Yandere Simulator High School: Hide and Seek" map from the following website:

[https://www.minecraftmaps.com/pvp-maps/yandere-simulator-high-school-hide-and-seek](https://www.minecraftmaps.com/pvp-maps/yandere-simulator-high-school-hide-and-seek)

But mc2mt fails with the following error:

```
Converting r.-2.1.mca file 0 of 17
Traceback (most recent call last):
  File "/home/rafael/.local/bin/mc2mt", line 123, in <module>
    converted_section = convertSection(found_section)
  File "/home/rafael/Caixa/Projetos/Minetest/mc2mt/section_conversion.py", line 22, in convertSection
    if section["blocks"].is_empty():
  File "/home/rafael/.local/lib/python3.8/site-packages/quarry/types/chunk.py", line 360, in is_empty
    return self.non_air == 0
  File "/home/rafael/.local/lib/python3.8/site-packages/quarry/types/chunk.py", line 365, in non_air
    self._non_air = [
  File "/home/rafael/.local/lib/python3.8/site-packages/quarry/types/chunk.py", line 365, in <listcomp>
    self._non_air = [
  File "/home/rafael/.local/lib/python3.8/site-packages/quarry/types/chunk.py", line 459, in __iter__
    value = self.palette[value]
IndexError: list index out of range
```

**Comment by jonajames** [comment]
This seems to be an issue with the quarry library not being able to convert the map.
Make sure you have the lastest version of the library.
If you installed it from pip, then remove it and download version from github:
https://github.com/barneygale/quarry
Unpack and run:
`python setup.py build`
`python setup.py install`
Or maybe this should also do the trick
`pip install --upgrade -e git+https://github.com/barneygale/quarry.git`

See if this solves the issue, looking from past issues this should have been already resolved.

**Comment by subpop** [comment]
I tried installing quarry from the upstream source, and my kids' minecraft world I'm trying to convert still crashes with this error. It happens in my `r.-1.-2.mca` file. I can provide the file if that helps, or I can try running a stripped down script that just converts that section, if that helps.

**Comment by jonajames** [comment]
Judging by the file name (-1,-2) and by looking into the issue this is probably an empty map region and quarry is failing to recognize it.
I patched the code to simply ignore the error and tried converting riosdev map, which worked for me.
Can you test it out?

**Comment by subpop** [comment]
Yea, so that definitely fixed the crash. And it does get through an entire conversion, but with a bunch of `BufferUnderrun` errors.

```
Converting r.1.1.mca file 53 of 54
Failed loading chunk: 17 18
Reason: BufferUnderrun
```

The resulting world is missing huge sections too, but it converted without crashing!

**Comment by jonajames** [comment]
I am aware of buffer underruns, it's yet another problem with the quarry library which does the actual .MCA conversion.
Since I never owned a copy of Minecraft my ability to fix the issue is very limited.
If you can/want to help providing some minimal maps (a single mca file is ok) I will try looking into the issue.

**Comment by subpop** [comment]
Sure, I've attached r.1.1.mca, which I know throws a buffer underrun. It's not very large though. I can provide another larger mca file if you want, but I'm not sure which ones throw the error.
[r.1.1.zip](https://github.com/jonajames/mc2mt/files/5976883/r.1.1.zip)

**Comment by jonajames** [comment]
Thanks, I think i will switch library to https://github.com/twoolie/NBT cause it seems it does the job better...

**Comment by subpop** [comment]
Let me know when you have a branch or version that uses that library. I'd be happy to run it against this entire set of region files.

**Comment by jonajames** [comment]
Now! it seems to be working better and faster. I've tried the "hide and seek" map and I had no problems during the conversion

**Comment by subpop** [comment]
Awesome! I just ran it again on my test world. This time, a new stack trace.

```
Traceback (most recent call last):
  File "/home/link/Sources/mc2mt/mc2mt.py", line 55, in <module>
    converted = section_conversion.convert_section(
  File "/home/link/Sources/mc2mt/mc2mtlib/section_conversion.py", line 38, in convert_section
    converted_blocks[block] = block_conversion.convert_block(block)
  File "/home/link/Sources/mc2mt/mc2mtlib/block_conversion.py", line 69, in convert_block
    converted = get_from_table(mod_table,block)
  File "/home/link/Sources/mc2mt/mc2mtlib/block_conversion.py", line 57, in get_from_table
    param2 = (globals()[param2[1:]])(block)
  File "/home/link/Sources/mc2mt/mc2mtlib/block_functions.py", line 52, in level2flowingliquid
    return int(str(block.properties["level"]))//2
KeyError: 'level'
```

**Comment by jonajames** [comment]
I fixed it.
